name: Check SpotifyD Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 6'

jobs:
  updateSpotifyD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install libs
        run: sudo apt-get update && sudo apt-get install curl jq -y
      
      - name: Get Latest SpotifyD Commit Hash
        id: spotifyd-hash
        run: |
          latest_commit_hash=$(curl -sL https://api.github.com/repos/Spotifyd/spotifyd/commits/master | jq -r ".sha")
          echo "latest_commit_hash=${latest_commit_hash}" >> $GITHUB_OUTPUT
          current_commit_hash=$(<spotifyd-hash.txt)
          echo "current_commit_hash=${current_commit_hash}" >> $GITHUB_OUTPUT
      
      - name: Update SpotifyD Hash
        if: steps.spotifyd-hash.outputs.current_commit_hash != steps.spotifyd-hash.outputs.latest_commit_hash
        env:
          LATEST_COMMIT_HASH: ${{ steps.spotifyd-hash.outputs.latest_commit_hash }}
        run: |
          # Update current commit hash
          echo ${{ steps.spotifyd-hash.outputs.latest_commit_hash }} > spotifyd-hash.txt
      
      - name: Update Readme.md & Dockerfile
        uses: jacobtomlinson/gha-find-replace@3.0.2
        with:
          find: ${{ steps.spotifyd-hash.outputs.current_commit_hash }}
          replace: ${{ steps.spotifyd-hash.outputs.latest_commit_hash }}
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update spotifyd-hash to ${{ steps.spotifyd-hash.outputs.latest_commit_hash }}
          title: Update spotifyd-hash to ${{ steps.spotifyd-hash.outputs.latest_commit_hash }}
          body: |
            Updates [spotifyd-hash][1] to ${{ steps.spotifyd-hash.outputs.latest_commit_hash }}
            Auto-generated by [create-pull-request][2]
            [1]: https://github.com/Spotifyd/spotifyd
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
          branch: spotifyd-update-nightly
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
