name: ci
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'spotifyd-hash.txt'
    branches:
      - '**'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: ShubhamTatvamasi/free-disk-space-action@master
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Version
        id: get_version
        uses: dhkatz/get-version-action@v3.0.0

      - name: Read Spotifyd Version
        id: read_version
        run: |
          VERSION=$(cat spotifyd-version.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Spotifyd Version: $VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Build alsa
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          target: alsa-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Build alsa-dbus
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          target: alsa-dbus-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Build pulseaudio
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          target: pulseaudio-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Build pulseaudio-dbus
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          target: pulseaudio-dbus-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}