name: ci
on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - '**'

jobs:
  buildx:
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        profile: [alsa, alsa-dbus, pulseaudio, pulseaudio-dbus]
    #concurrency: 
    #  group: ${{ github.workflow }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2.3.0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-${{ matrix.profile }}
          key: ${{ runner.os }}-${{ github.sha }}-${{ matrix.profile }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.sha }}-${{ matrix.profile }}-buildx-
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Build only
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.${{ matrix.profile }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          cache-from: type=local,src=/tmp/.buildx-cache-${{ matrix.profile }}
          cache-to: type=local,dest=/tmp/.buildx-cache-new-${{ matrix.profile }}
      - 
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache-${{ matrix.profile }}
          mv /tmp/.buildx-cache-new-${{ matrix.profile }} /tmp/.buildx-cache-${{ matrix.profile }}
      