# No need for a nightly ci as if it fails it fails
name: nightly
on:
  push:
    branches:
      - main
    paths:
      - 'spotifyd-hash.txt'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space
        uses: ShubhamTatvamasi/free-disk-space-action@master
      
      - name: Checkout
        uses: actions/checkout@v5

      - name: Get Version
        id: get_version
        uses: dhkatz/get-version-action@v3.0.0

      - name: Read Spotifyd Version
        id: read_version
        run: |
          VERSION=$(cat spotifyd-hash.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Spotifyd Version: $VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }}

      - name: Push alsa
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          target: alsa-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          tags: |
            hvalev/spotifyd-alsa:${{ env.VERSION }}
            hvalev/spotifyd-alsa:nightly

      - name: Push alsa-dbus
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          target: alsa-dbus-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          tags: |
            hvalev/spotifyd-alsa-dbus:${{ env.VERSION }}
            hvalev/spotifyd-alsa-dbus:nightly

      - name: Push pulseaudio
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          target: pulseaudio-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          tags: |
            hvalev/spotifyd-pulseaudio:${{ env.VERSION }}
            hvalev/spotifyd-pulseaudio:nightly

      - name: Push pulseaudio-dbus
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          target: pulseaudio-dbus-release
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.VERSION }}
          push: true
          tags: |
            hvalev/spotifyd-pulseaudio-dbus:${{ env.VERSION }}
            hvalev/spotifyd-pulseaudio-dbus:nightly

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBPWD }}
          repository: hvalev/spotifyd-alsa

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBPWD }}
          repository: hvalev/spotifyd-alsa-dbus

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBPWD }}
          repository: hvalev/spotifyd-pulseaudio
      
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBPWD }}
          repository: hvalev/spotifyd-pulseaudio-dbus